### ISSUE TITLE
English app preferences have German explanations

### ISSUE THREAD

**Issue by Solomon1732** [markusfisch/Libra#14]
I'd expect an English menu to have English explanations to preferences. As it stands, I don't understand much of what is going on there.
![Screenshot_20221231_183505_Decisions](https://user-images.githubusercontent.com/16454223/210149966-5da322ad-7012-42df-8df2-1fda6504683b.jpg)

**Comment by markusfisch** [comment]
Hm, very strange 🤔  These are ordinary string resources Android is managing. The app also contains the english strings but somehow isn't using them.

Thanks for filing an issue 👍

**Comment by markusfisch** [comment]
Fixed in the latest version, 1.12.3, which is already available on Google Play.
