### ISSUE TITLE
fdroid repository

### ISSUE THREAD

**Issue by Arnaudv6** [markusfisch/Libra#2]
Hello Markus
I went through your projects and stumbled on this:
Libra would gain some exposition if present in fdroid I think,
and I'll wait for this before I give it a go.
More generally, thanks for contributing that much projects to open source community in the first place.

**Comment by markusfisch** [comment]
I would love to see Libra on F-Droid! 👍 So if you like to file it in there, please do so! The only reason I haven't done it myself is that I haven't had the time yet 🙈 

Since I'm using mostly open source myself, it feels more like giving back something 😄

**Comment by Arnaudv6** [comment]
I think there is a good hint here:
https://github.com/HackMyChurch/aelf-dailyreadings/pull/34

**Comment by rugk** [comment]
It would be great to see this Android app on F-Droid!

[F-Droid](https://f-droid.org/) is an Android app store specifically for free/libre open-source apps. It would be great if your app could be released there, as it is the number one for getting FLOSS Android apps for many people.
F-Droid also builds all apps from source ([optionally even reproducible](https://f-droid.org/en/docs/Reproducible_Builds/)), so downloads from there can be trusted.

The [app developer FAQ](https://f-droid.org/en/docs/FAQ_-_App_Developers/) or [the quick start guide](https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/) may help you to get started.

**Comment by fossdd** [comment]
RFP is opened and @FestplattenSchnitzel opened a MR for the app inclusion.
