### ISSUE TITLE
[Important Feature]:  Manual Sorting

### ISSUE THREAD

**Issue by Glitchy-Tozier** [markusfisch/Libra#3]
Hey, I love your app Idea! 
Here's one further improvement that I think is most important right now:

### Improvement
Add the ability to sort arguments for one topic manually via drag & drop. 

### Why do I think this is important?
Because it is handy to structure your pro&con arguments in a way such that they resemble a real back and forth.

Example:
                +7 Jogging is good for your health
-3 But it's difficult to find the time.
                +3 Working on getting such an activity into your daily routine will be a good practice.
-2 I might not have the time to do it every day at the same time.
-1 Which might make it difficult to form the habit.
....
And so on.

Now, because I clicked the [order entries] button, a long chain of arguments is competely distorted, which is really unfortunate and re-writing the whole thing is not fun at all.
(Also, it might be a good idea to warn users the first time they click the [order entries] button.

**Comment by markusfisch** [comment]
Hi, I'm sorry for the inconvenience 😬

Actually, it's quite easy to add another menu item to restore the original positions - so I already did this yesterday 😉 Now I'm working on manual sorting, and I hope to release an update later this week.

**Comment by Glitchy-Tozier** [comment]
Amazing, thanks!  :)

**Comment by markusfisch** [comment]
Version 1.10.0 should become available in the next few hours and supports restoring the original input positions as well as manual sorting.

However, sorting doesn't work with Drag'n Drop yet, but there is an up and a down arrow in the context menu beside the trash can when an argument is selected.

I going to add Drag'n Drop too, but this will take more a bit more time, unfortunately.

**Comment by Glitchy-Tozier** [comment]
It worked, nice work!  :)
