### ISSUE TITLE
Cursor should be at the end of the edited argument

### ISSUE THREAD

**Issue by jetrosut** [markusfisch/Libra#7]
When you tap an argument because you want to edit it (for me, it's mostly to change the phrasing or fix typos), the cursor goes to the beginning of the line. It would be great if it was at the end of the line instead, which would make adding more information and correcting typos easier.

**Comment by markusfisch** [comment]
Good idea! 👍 Will change the behavior in the next version.

**Comment by markusfisch** [comment]
Implemented in https://github.com/markusfisch/Libra/commit/4ee487ddee9e47a585226b0fb7df12e730962121

Available in version 1.12.1 which should become available on Google Play within the next few hours. F-Droid probably tomorrow. Or directly from here:
https://github.com/markusfisch/Libra/releases/tag/1.12.1
